# Generated by Django 5.0.6 on 2024-09-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_from', models.CharField(max_length=30, null=True)),
                ('route_to', models.CharField(max_length=30, null=True)),
                ('sender_name', models.CharField(max_length=50, null=True)),
                ('sender_mobile', models.CharField(max_length=50, null=True)),
                ('sender_email', models.CharField(max_length=50, null=True)),
                ('sender_address', models.CharField(max_length=50, null=True)),
                ('sender_company', models.CharField(max_length=50, null=True)),
                ('sender_GST', models.CharField(max_length=50, null=True)),
                ('receiver_name', models.CharField(max_length=50, null=True)),
                ('receiver_mobile', models.CharField(max_length=50, null=True)),
                ('receiver_email', models.CharField(max_length=50, null=True)),
                ('receiver_address', models.CharField(max_length=50, null=True)),
                ('receiver_company', models.CharField(max_length=50, null=True)),
                ('receiver_GST', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
