# Generated by Django 5.0.6 on 2024-09-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0002_parties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parties',
            name='receiver_company',
        ),
        migrations.RemoveField(
            model_name='parties',
            name='receiver_email',
        ),
        migrations.RemoveField(
            model_name='parties',
            name='sender_company',
        ),
        migrations.RemoveField(
            model_name='parties',
            name='sender_email',
        ),
    ]
