# Generated by Django 5.0.6 on 2024-09-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0003_remove_parties_receiver_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignee',
            name='receiver_company',
        ),
        migrations.RemoveField(
            model_name='consignee',
            name='receiver_email',
        ),
        migrations.RemoveField(
            model_name='consignor',
            name='sender_company',
        ),
        migrations.RemoveField(
            model_name='consignor',
            name='sender_email',
        ),
    ]
