# Generated by Django 5.0.6 on 2024-09-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0004_remove_consignee_receiver_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='payment_mode',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='payment_mode',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
