# Generated by Django 5.0.6 on 2024-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='category',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='category',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
