# Generated by Django 5.0.6 on 2024-09-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0008_category_cahregweight_category_frieght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cahregweight',
            new_name='charge_weight',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='frieght',
            new_name='freight',
        ),
    ]
