# Generated by Django 5.0.6 on 2024-09-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0009_rename_cahregweight_category_charge_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='door_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='freight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='hamali',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='st_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
