# Generated by Django 5.0.6 on 2024-09-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0010_alter_addconsignmenttemp_door_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='weightAmt',
            field=models.FloatField(null=True),
        ),
    ]
