# Generated by Django 5.0.6 on 2024-09-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0011_alter_addconsignmenttemp_weightamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='barcode',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='barcode',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
