# Generated by Django 5.0.6 on 2024-09-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0012_addconsignment_barcode_addconsignmenttemp_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addconsignment',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='barcode',
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
