# Generated by Django 5.0.6 on 2024-09-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0013_remove_addconsignment_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addconsignment',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='commission',
        ),
    ]
