# Generated by Django 5.0.6 on 2024-09-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0016_tripsheetprem_prod_price_tripsheettemp_prod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='track_number',
            field=models.CharField(max_length=50),
        ),
    ]
