# Generated by Django 5.0.6 on 2024-09-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0018_disel_rename_ltrate_tripsheettemp_weightamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsheetprem',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tripsheettemp',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
