# Generated by Django 5.0.6 on 2024-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0019_tripsheetprem_weight_tripsheettemp_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsheetprem',
            name='prod_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tripsheettemp',
            name='prod_price',
            field=models.FloatField(null=True),
        ),
    ]
