# Generated by Django 5.0.6 on 2024-09-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0020_tripsheetprem_prod_price_tripsheettemp_prod_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripsheetprem',
            old_name='desc',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='tripsheettemp',
            old_name='desc',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='desc_product',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='prod_invoice',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='weightAmt',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='desc_product',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='prod_invoice',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='weightAmt',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tripsheetprem',
            name='weightAmt',
        ),
        migrations.RemoveField(
            model_name='tripsheettemp',
            name='weightAmt',
        ),
    ]
