# Generated by Django 5.0.6 on 2024-09-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0021_rename_desc_tripsheetprem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='category',
            name='charge_weight',
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='remark',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='remark',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
