# Generated by Django 5.0.6 on 2024-09-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0022_remove_branch_gst_remove_category_charge_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='door_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='freight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='hamali',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='st_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
