# Generated by Django 5.0.6 on 2024-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0024_alter_addconsignment_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(null=True)),
                ('LrNo', models.CharField(max_length=150, null=True)),
                ('stage', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150, null=True)),
                ('Branch', models.CharField(max_length=150, null=True)),
                ('branchlocation', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
