# Generated by Django 5.0.6 on 2024-09-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0025_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='Time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stages',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
