# Generated by Django 5.0.6 on 2024-10-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0026_stages_time_alter_stages_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addconsignment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='payment_mode',
        ),
    ]
