# Generated by Django 5.0.6 on 2024-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0027_remove_addconsignment_payment_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignment',
            old_name='st_charge',
            new_name='CGST',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='st_charge',
            new_name='CGST',
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='GST',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='SGST',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='GST',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='SGST',
            field=models.FloatField(null=True),
        ),
    ]
