# Generated by Django 5.0.6 on 2024-10-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0028_rename_st_charge_addconsignment_cgst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignment',
            old_name='CGST',
            new_name='cgst',
        ),
        migrations.RenameField(
            model_name='addconsignment',
            old_name='GST',
            new_name='gst',
        ),
        migrations.RenameField(
            model_name='addconsignment',
            old_name='SGST',
            new_name='sgst',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='CGST',
            new_name='cgst',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='GST',
            new_name='gst',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='SGST',
            new_name='sgst',
        ),
    ]
