# Generated by Django 5.0.6 on 2024-10-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0029_rename_cgst_addconsignment_cgst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=50, null=True)),
                ('sender_name', models.CharField(max_length=50, null=True)),
                ('sender_mobile', models.CharField(max_length=50, null=True)),
                ('sender_address', models.CharField(max_length=50, null=True)),
                ('receiver_name', models.CharField(max_length=50, null=True)),
                ('receiver_mobile', models.CharField(max_length=50, null=True)),
                ('receiver_address', models.CharField(max_length=50, null=True)),
                ('total_cost', models.FloatField(null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('pay_status', models.CharField(max_length=30, null=True)),
                ('route_from', models.CharField(max_length=30, null=True)),
                ('route_to', models.CharField(max_length=30, null=True)),
                ('pieces', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('eway_bill', models.CharField(max_length=150, null=True)),
                ('category', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
