# Generated by Django 5.0.6 on 2024-10-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0030_consignmenthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignmenthistory',
            old_name='branch',
            new_name='commit',
        ),
    ]
