# Generated by Django 5.0.6 on 2024-10-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0031_rename_branch_consignmenthistory_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='reason',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='reason',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
