# Generated by Django 5.0.6 on 2024-10-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0032_addconsignment_reason_addconsignment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='created_at',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
