# Generated by Django 5.0.6 on 2024-10-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0033_rename_created_at_location_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
