# Generated by Django 5.0.6 on 2024-10-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0035_addconsignment_location_addconsignmenttemp_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
