# Generated by Django 5.0.6 on 2024-10-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0037_rename_location_addconsignment_receiver_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addconsignment',
            name='receiver_location',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='sender_location',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='receiver_location',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='sender_location',
        ),
    ]
