# Generated by Django 5.0.6 on 2024-10-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0038_remove_addconsignment_receiver_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='consignor',
            name='location',
        ),
        migrations.AddField(
            model_name='consignee',
            name='receiver_password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='sender_password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='branch',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='receiver_GST',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='receiver_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='receiver_mobile',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='receiver_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignor',
            name='branch',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignor',
            name='sender_GST',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignor',
            name='sender_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignor',
            name='sender_mobile',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignor',
            name='sender_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
