# Generated by Django 5.0.6 on 2024-10-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0040_consignee_username_consignor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripsheetprem',
            name='LTRate',
        ),
        migrations.RemoveField(
            model_name='tripsheetprem',
            name='Ltr',
        ),
    ]
