# Generated by Django 5.0.6 on 2024-10-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0041_remove_tripsheetprem_ltrate_remove_tripsheetprem_ltr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripsheetprem',
            name='st_charge',
        ),
    ]
