# Generated by Django 5.0.6 on 2024-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0042_remove_tripsheetprem_st_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages',
            name='Time',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
